### ISSUE TITLE
[FEATURE] Produce

### ISSUE THREAD

**Issue by Biosmatrix** [BuildForSDG/team-010-frontend#6]
### Todo

**Produce**
*As a user, I should be able to*,

-  [View all produce](https://github.com/BuildForSDG/team-010-frontend/wiki/%5BSTORY%5D-A-user-should-be-able-to-view-all-produce)

*As a user, I should be able to*
-  [search for produce of a specific category](https://github.com/BuildForSDG/team-010-frontend/wiki/%5BSTORY%5D-A-user-should-be-able-to-search-for-produce-of-a-specific-category)

*As a farmer, I should be able to*
 - [Post a new produce](https://github.com/BuildForSDG/team-010-frontend/wiki/%5BSTORY%5D-A-farmer-should-be-able-to-post-a-new-produce)

*As a farmer, I should be able to*
 -   [update a produce](https://github.com/BuildForSDG/team-010-frontend/wiki/%5BSTORY%5D-A-posted-produce-should-be-able-to-be-marked-as-out-of-stock,-updated-or-deleted-by-a-farmer)

*As a farmer, I should be able to*
 -   [Mark a produce as out of stock](https://github.com/BuildForSDG/team-010-frontend/wiki/%5BSTORY%5D-A-posted-produce-should-be-able-to-be-marked-as-out-of-stock,-updated-or-deleted-by-a-farmer)

*As a farmer, I should be able to*
 -   [deleted a produce](https://github.com/BuildForSDG/team-010-frontend/wiki/%5BSTORY%5D-A-posted-produce-should-be-able-to-be-marked-as-out-of-stock,-updated-or-deleted-by-a-farmer)

**Comment by orimdominic** [comment]
1. Is there a UI mockup for this already or I'm developing one myself? 
2. Can I be directed to where I can get the `Produce` schema
3. I also need the API for the CRUD

Thanks
 @RuthChisom @Biosmatrix

**Comment by RuthChisom** [comment]
@sudo-kaizen sorry @nues1979 is already working on this. I'd reassign you. Thanks
